language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10.24.1'
before_script:
  - npm run warn-upper
  - npm run stop-upper
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
